### ISSUE TITLE
Videos in Media Browser light box cannot be resized

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#28]
Hi,  I'm trying to create a Media Browser to show a selection of videos.  Perhaps I'm doing something wrong, but whatever I do with regards to resizing the caption and title in the lightbox, as suggested by the tutorial, the video is still occupying only perhaps 40% of the screen, with a lot of wasted space at the sides and bottom of  screen.  I've also used ffmpeg to rescale the videos, but that does not appear to affect the resulting size on screen at all.  It would be ideal (particularly when there isn't a caption/credit) to be able to use most of the screen real estate for the actual video content.

FYI I'm using Exhibitera 5.1.

Thanks.

**Comment by forceflow1049** [comment]
Hi, @David-S-Morgan, this is definitely a bug. When changing the amount of space allocated to the title, caption, or credit, the changes were only being applied to images in the lightbox, not videos.

I've fixed that in https://github.com/Cosmic-Chatter/Exhibitera/tree/5.1_Media_Browser_video_height if you would like to build 5.1 for yourself. Otherwise, the fix has been incorporated into 5.2.

**Comment by David-S-Morgan** [comment]
Great -- I was already fiddling with building the 5.1 source, so I will
update and test again.  Thanks.
